version: "3.3"

services:
  notebook:
    container_name: frre_jupyter
    environment:
      - PASSWORD=utnfrre
    ports:
      - "10000:8888"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/home/jovyan/work